version: '3.8'

networks:
  greenisland-net:
    name: greenisland-net
  

services:
  nats:
    image: bitnami/nats:2
    command: ["nats-server", "--jetstream", "-c", "/etc/nats.conf"]
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats-data:/opt/bitnami/nats
      - $PWD/configs/nats.conf:/etc/nats.conf:ro
    networks:
      - greenisland-net

volumes:
  nats-data: {}
